name: "godot-ci manual export"
on:
 workflow_dispatch:

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: Mario-Forever-Community-Edition
  PROJECT_PATH: .

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04
    container:
      image: jue13/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --import
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          echo "nightly-linux\n${{ github.sha }}" > stages/main_menu/version-text.txt
          godot --headless --verbose --export-release "Linux/X11" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - name: Checkout Skins
        uses: actions/checkout@v4
        with:
          repository: meteo-dream/bundled-mfce-skins
          path: build/linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
