name: "godot-ci export"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: Mario-Forever-Community-Edition
  PROJECT_PATH: .
  UPLOAD_FOLDER: MFCE-Builds

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04  # Using 24.04 due to libgdmpt extension (for audio playback) failing on 22.04
    container:
      image: jue13/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set WINEPREFIX
        run: echo WINEPREFIX=/root/.wine >> "$GITHUB_ENV"
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Project Import
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose --import
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          echo "nightly-win64\n${{ github.sha }}" > stages/main_menu/version-text.txt
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3' > "$EXPORT_DIR/windows/01. Compatibility Mode.bat"
          echo 'start "" ".\${{ env.EXPORT_NAME }}.exe" --rendering-driver opengl3_angle' > "$EXPORT_DIR/windows/02. Compatibility Mode (angle).bat"
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Prepare For Upload
        run: |
          EXPORT_DIR="$(readlink -f build)"
          echo "MFCE Build: [$(echo "${{ github.sha }}" | cut -c 1-7)](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) from $(date '+%d-%b-%Y %T')" > "$EXPORT_DIR/Readme.md"
          cd $EXPORT_DIR
          cp Readme.md windows/Readme.md
          zip -r build_windows.zip windows
          rm -rf windows
          split -b 80M build_windows.zip part_ -d --verbose
      - name: Upload Files
        run: |
          EXPORT_DIR="$(readlink -f build)"
          FILE_SIZE="$(wc -c < $EXPORT_DIR/build_windows.zip)"
          FOLDER_UUID="$(cat /proc/sys/kernel/random/uuid)"
          
          echo "Creating an upload folder: $FOLDER_UUID"
          curl -X MKCOL \
            -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
            ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/uploads/${{ secrets.NEXTCLOUD_USERNAME }}/$FOLDER_UUID \
            --header 'Destination: ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/${{ env.UPLOAD_FOLDER }}/build_windows.zip'
          
          LOOP_ID=0
          PART_ID=""
          for FILE in $EXPORT_DIR/part_*
          do
            LOOP_ID=$((LOOP_ID + 1))
            PART_ID=$(printf "%05d" "$LOOP_ID")
            echo "Uploading part $PART_ID: $FILE"
            curl -X PUT \
              -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
              ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/uploads/${{ secrets.NEXTCLOUD_USERNAME }}/$FOLDER_UUID/$PART_ID \
              --data-binary "@$FILE" \
              --header 'Destination: ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/${{ env.UPLOAD_FOLDER }}/build_windows.zip' \
              --header 'OC-Total-Length: $FILE_SIZE'
          done
          
          echo "Assembling the chunks"
          curl -X MOVE \
            -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
            ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/uploads/${{ secrets.NEXTCLOUD_USERNAME }}/$FOLDER_UUID/.file \
            --header 'Destination: ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/${{ env.UPLOAD_FOLDER }}/build_windows.zip' \
            --header 'OC-Total-Length: $FILE_SIZE'
          
          echo "Uploading file: $EXPORT_DIR/Readme.md"
          curl \
            -u ${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }} \
            -T "$EXPORT_DIR/Readme.md" \
            -g ${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/GitHub-Uploads/${{ env.UPLOAD_FOLDER }}/
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows
#          path: build/windows
